package com.mycompany.cashiokillshot.enums;

public enum RequestTypes {
    REGISTER_FIRM, GET_EMPLOYEE, DELETE_USER,
    REGISTER_EMPLOYEE, UPDATE_USER_PASSWORD, AUTHENTICATE, GET_FIRM,
    CHANGE_USER_STATUS, GET_USERS, GET_FIRMS, ADD_USER_CATEGORY,
    GET_USER_CATEGORIES, CREATE_USER, GET_FIRMS_WITH_ADMIN
}
