package com.mycompany.cashiokillshot.enums;

public enum ResultIds {
    REGISTRATION_SUCCESSFUL, REGISTRATION_FAILED, FIRMS, FIRMS_NOT_FOUND,VALIDATION_FAILED,AUTHENTICATION_SUCCESSFUL, AUTHENTICATION_FAILED, REQUEST_FAILED, REQUEST_SUCCESSFUL
}
